### ISSUE TITLE
Failure to generate dataset for `NLDHL_pvol_20200322T1900_6234.h5.csv.gz`

### ISSUE THREAD

**Issue by bart1** [point-cloud-radar/bird-cloud-gnn#99]
This is a quite a short file (probably one plane/boat annotated further away), reading results in the following error
```python
>>> dataset = RadarDataset(
...     "/home/bart/allLabels/NLDHL_pvol_20200322T1900_6234.h5.csv.gz",
...     features,
...     target,
...     num_neighbours=40,
...     max_poi_per_label=500,
... )
/home/bart/allLabels/NLDHL_pvol_20200322T1900_6234.h5.csv.gz
Traceback (most recent call last):
  File "/home/bart/bird-cloud-gnn/env/lib/python3.10/site-packages/pandas/core/indexing.py", line 1618, in _get_list_axis
    return self.obj._take_with_is_copy(key, axis=axis)
  File "/home/bart/bird-cloud-gnn/env/lib/python3.10/site-packages/pandas/core/generic.py", line 3948, in _take_with_is_copy
    result = self._take(indices=indices, axis=axis)
  File "/home/bart/bird-cloud-gnn/env/lib/python3.10/site-packages/pandas/core/generic.py", line 3932, in _take
    new_data = self._mgr.take(
  File "/home/bart/bird-cloud-gnn/env/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 960, in take
    indexer = maybe_convert_indices(indexer, n, verify=verify)
  File "/home/bart/bird-cloud-gnn/env/lib/python3.10/site-packages/pandas/core/indexers/utils.py", line 284, in maybe_convert_indices
    raise IndexError("indices are out-of-bounds")
IndexError: indices are out-of-bounds

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bart/bird-cloud-gnn/bird_cloud_gnn/radar_dataset.py", line 81, in __init__
    super().__init__(
  File "/home/bart/bird-cloud-gnn/env/lib/python3.10/site-packages/dgl/data/dgl_dataset.py", line 112, in __init__
    self._load()
  File "/home/bart/bird-cloud-gnn/env/lib/python3.10/site-packages/dgl/data/dgl_dataset.py", line 203, in _load
    self.process()
  File "/home/bart/bird-cloud-gnn/bird_cloud_gnn/radar_dataset.py", line 195, in process
    self._read_one_file(self.data_path)
  File "/home/bart/bird-cloud-gnn/bird_cloud_gnn/radar_dataset.py", line 107, in _read_one_file
    self._process_data(data, origin=data_path)
  File "/home/bart/bird-cloud-gnn/bird_cloud_gnn/radar_dataset.py", line 158, in _process_data
    local_xyz = data_xyz.iloc[indexes]
  File "/home/bart/bird-cloud-gnn/env/lib/python3.10/site-packages/pandas/core/indexing.py", line 1103, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/bart/bird-cloud-gnn/env/lib/python3.10/site-packages/pandas/core/indexing.py", line 1647, in _getitem_axis
    return self._get_list_axis(key, axis=axis)
  File "/home/bart/bird-cloud-gnn/env/lib/python3.10/site-packages/pandas/core/indexing.py", line 1621, in _get_list_axis
    raise IndexError("positional indexers are out-of-bounds") from err
IndexError: positional indexers are out-of-bounds
```

**Comment by bart1** [comment]
`NLHRW_pvol_20230201T1900_6356.h5.csv.gz` seems to fail with a similar error
